swagger: '2.0'
info:
    title: Authentication, Admin, and File APIs
    version: '1.0.0'
tags:
    - name: Authentication
      description: APIs for user authentication
    - name: Admin
      description: APIs for admin operations
    - name: Files
      description: APIs for file operations
paths:
    /login:
        post:
            summary: Authenticate user
            tags:
                - Authentication
            consumes:
                - application/x-www-form-urlencoded
            produces:
                - application/json
            parameters:
                - name: username
                  in: formData
                  required: true
                  type: string
                - name: password
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful login
                    schema:
                        type: object
                        properties:
                            isAdmin:
                                type: boolean
                            isAuthenticated:
                                type: boolean
                            token:
                                type: string
                    examples:
                        application/json:
                            {
                                'isAdmin': false,
                                'isAuthenticated': true,
                                'token': 'd387321daf04f6e79081efa9301a35297d76f93c52faa45ba0e4d371a7942e69',
                            }
                401:
                    description: Unauthorized
                    schema:
                        type: object
                        properties:
                            isAuthenticated:
                                type: boolean
                    examples:
                        application/json: { 'isAuthenticated': false }
    /isAuthenticated:
        post:
            summary: Check authentication status
            tags:
                - Authentication
            consumes:
                - application/x-www-form-urlencoded
            produces:
                - application/json
            parameters:
                - name: token
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful authentication
                    schema:
                        type: object
                        properties:
                            isAuthenticated:
                                type: boolean
                            isAdmin:
                                type: boolean
                    examples:
                        application/json:
                            { 'isAuthenticated': true, 'isAdmin': false }
                401:
                    description: Unauthorized
                    schema:
                        type: object
                        properties:
                            isAuthenticated:
                                type: boolean
                    examples:
                        application/json: { 'isAuthenticated': false }
    /admin:
        post:
            summary: Fetch logs
            tags:
                - Admin
            consumes:
                - application/x-www-form-urlencoded
            produces:
                - application/json
            parameters:
                - name: token
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful operation
                    schema:
                        type: object
                        properties:
                            logs:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        ID:
                                            type: integer
                                        LOB_NAME:
                                            type: string
                                        USERNAME:
                                            type: string
                                        CONVERSIONSTATUS:
                                            type: boolean
                                        CONVERTEDON:
                                            type: string
                                        FILETYPE:
                                            type: string
                                        UPLOADEDFILENAME:
                                            type: string
                                        CONVERTEDFILENAME:
                                            type: string
                    examples:
                        application/json:
                            {
                                'logs':
                                    [
                                        {
                                            'ID': 6,
                                            'LOB_NAME': 'DPP',
                                            'USERNAME': 'DPP_20168',
                                            'CONVERSIONSTATUS': true,
                                            'CONVERTEDON': '23 May 2023, 11:14 AM',
                                            'FILETYPE': 'PDM',
                                            'UPLOADEDFILENAME': 'instanceFile-1684840473548-606610341.json, bindedFiles-1684840473548-848518405.json, bindedFiles-1684840473549-177092127.json',
                                            'CONVERTEDFILENAME': 'converted-1684840473560-279176915.json',
                                        },
                                        {
                                            'ID': 7,
                                            'LOB_NAME': 'DPP',
                                            'USERNAME': 'DPP_20168',
                                            'CONVERSIONSTATUS': true,
                                            'CONVERTEDON': '23 May 2023, 11:15 AM',
                                            'FILETYPE': 'PDM',
                                            'UPLOADEDFILENAME': 'instanceFile-1684840505631-901242957.json, bindedFiles-1684840505632-118144587.json, bindedFiles-1684840505634-457846469.json',
                                            'CONVERTEDFILENAME': 'converted-1684840505647-569076059.json',
                                        },
                                    ],
                            }
                400:
                    description: Bad request
                    schema:
                        type: object
                    examples:
                        application/json: 'Missing token in request'
                401:
                    description: Unauthorized
                    schema:
                        type: object
                    examples:
                        application/json: 'User is not admin'
                500:
                    description: Internal server error
                    schema:
                        type: object
                    examples:
                        application/json: 'Error in fetching logs'
    /admin/generate-credentials:
        post:
            summary: Generate credentials
            tags:
                - Admin
            consumes:
                - application/x-www-form-urlencoded
            produces:
                - application/json
            parameters:
                - name: token
                  in: formData
                  required: true
                  type: string
                - name: lob_name
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful credentials generation
                    schema:
                        type: object
                        properties:
                            username:
                                type: string
                            password:
                                type: string
                    examples:
                        application/json:
                            {
                                'username': 'BTP_42771',
                                'password': '4Iw$Uij*42771',
                            }
                401:
                    description: Unauthorized
                    schema:
                        type: object
                    examples:
                        application/json: 'Invalid token'
                400:
                    description: Bad Request
                    schema:
                        type: object
                    examples:
                        application/json: 'Missing token in request'
    /file-upload:
        post:
            summary: Upload files
            tags:
                - Files
            consumes:
                - multipart/form-data
            produces:
                - application/json
            parameters:
                - name: instanceFile
                  in: formData
                  required: true
                  type: file
                - name: bindedFiles
                  in: formData
                  required: false
                  type: array
                  items:
                      type: file
                - name: fileType
                  in: formData
                  required: true
                  type: string
                - name: username
                  in: formData
                  required: true
                  type: string
                - name: lob_name
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful file upload
                    schema:
                        type: object
                        properties:
                            fileName:
                                type: string
                    examples:
                        application/json:
                            {
                                'fileName': 'converted-1685954254631-556973628.json',
                            }
                400:
                    description: Bad Request
                    schema:
                        type: object
                    examples:
                        application/json: 'Invalid request payload'
                500:
                    description: Internal Server Error
                    schema:
                        type: object
                    examples:
                        application/json: 'Error in reading the files'
    /file-download:
        post:
            summary: Download file
            tags:
                - Files
            consumes:
                - application/x-www-form-urlencoded
            produces:
                - application/octet-stream
            parameters:
                - name: fileName
                  in: formData
                  required: true
                  type: string
            responses:
                200:
                    description: Successful file download
                400:
                    description: Bad Request
                    schema:
                        type: object
                    examples:
                        application/json: 'Missing filename!'
                500:
                    description: Internal Server Error
                    schema:
                        type: object
                    examples:
                        application/json: 'Error in file download'
definitions:
    Log:
        type: object
        properties:
            ID:
                type: integer
            LOB_NAME:
                type: string
            USERNAME:
                type: string
            CONVERSIONSTATUS:
                type: boolean
            CONVERTEDON:
                type: string
            FILETYPE:
                type: string
            UPLOADEDFILENAME:
                type: string
            CONVERTEDFILENAME:
                type: string
